# -*- coding: utf-8 -*-
"""testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unmi5Jt-cXAZVlvqSzfoHHYpvRo7jwwZ
"""

import torch
import torch.nn as nn
from .models import CustomMobileNet

torch.cuda.is_available()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

model = CustomMobileNet(7)
model = model.to(device)

from torch.utils.data import DataLoader, random_split
from torchvision import datasets, transforms

transform = transforms.Compose(
    [
        transforms.Resize((128, 128)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ]
)

ds = datasets.ImageFolder(
    root="C:/Users/Rey/Desktop/Projects/raf-db/train/", transform=transform
)

test_loader = DataLoader(ds, batch_size=32, num_workers=4, pin_memory=True)
